[project]
name = "svc1"
version = "0.7.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Todd Jacobsen", email = "yolabingo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "core",
]

[project.scripts]
svc1 = "svc1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
core = { workspace = true }
