[project]
name = "core"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Todd Jacobsen", email = "yolabingo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "attrs>=25.3.0",
    "invoke>=2.2.0",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]

[project.scripts]
core = "core:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
