name: Validate PR title and commits

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          validateSingleCommit: true  # if PR has only one commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}