name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv lock && uv sync --locked --all-extras --dev
