name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Python
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-python-${{ hashFiles('.python-version') }}
          restore-keys: |
            ${{ runner.os }}-python-
      
      - name: Install uv with cache
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Ruff lint and format
        uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

      - name: Install the project
        run: uv lock && uv sync --locked --all-extras --dev