name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run in debug mode'
        required: false
        default: 'true'

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      uvws--tag_name: ${{ steps.release.outputs.uvws--tag_name}}
      uvws--release_created: ${{ steps.release.outputs.uvws--release_created}}
      core--tag_name: ${{ steps.release.outputs.core--tag_name}}
      core--release_created: ${{ steps.release.outputs.core--release_created}}
      svc1--tag_name: ${{ steps.release.outputs.svc1--tag_name}}
      svc1--release_created: ${{ steps.release.outputs.svc1--release_created}}
    steps:
      - name: Acquire lock
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release-please
          
      - name: Debug Info
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug == 'true' }}
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          ls -la
          cat release-please-config.json
          
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          include-component-in-tag: true
          target-branch: release-please
       
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Update uv.lock after release-please bumps versions
        run: uv lock
  