name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: uvws
          monorepo-tags: true