name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run in debug mode'
        required: false
        default: 'false'

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Debug Info
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug == 'true' }}
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          ls -la
          cat release-please-config.json
          
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: python
          config-file: release-please-config.json
          include-component-in-tag: true
          monorepo-tags: true
          package-name: uvws
